// Generated by CoffeeScript 1.6.2
(function() {
  var jct, myApp;

  myApp = angular.module("myApp", ['gold', 'teamService', 'playerService']);

  myApp.config([
    "$locationProvider", "$routeProvider", function($locationProvider, $routeProvider) {
      var base;

      $locationProvider.html5Mode(true);
      base = '/owd';
      $routeProvider.when("" + base + "/app", {
        templateUrl: "" + base + "/static/files/home.html",
        controller: "HomeCtlr"
      }).when("" + base + "/app/team", {
        templateUrl: "" + base + "/static/files/team.html",
        controller: "TeamCtlr"
      }).when("" + base + "/app/team/:tid", {
        templateUrl: "" + base + "/static/files/team.html",
        controller: "TeamCtlr"
      }).when("" + base + "/app/player", {
        templateUrl: "" + base + "/static/files/player.html",
        controller: "PlayerCtlr"
      }).when("" + base + "/app/player/:pid", {
        templateUrl: "" + base + "/static/files/player.html",
        controller: "PlayerCtlr"
      }).otherwise({
        redirectTo: "" + base + "/app"
      });
      return true;
    }
  ]);

  myApp.controller('NavbarCtlr', [
    '$scope', '$routeParams', '$location', '$route', function($scope, $routeParams, $location, $route) {
      var _ref;

      $scope.location = $location;
      $scope.route = $route;
      $scope.winLoc = window.location;
      console.log("NavbarCtlr");
      $scope.alertMsg = '';
      $scope.navActive = {
        'home': 'inactive',
        'team': 'inactive',
        'player': 'inactive'
      };
      if ((_ref = $scope.pathNav) == null) {
        $scope.pathNav = {
          "/app$": "home",
          "/app/team": "team",
          "/app/player": "player"
        };
      }
      $scope.activateNav = function(nav) {
        var x;

        $scope.navActive[nav] = 'active';
        for (x in $scope.navActive) {
          if (x !== nav) {
            $scope.navActive[x] = 'inactive';
          }
        }
        return true;
      };
      $scope.updateNav = function(newPath, oldPath) {
        var nav, path, _ref1;

        _ref1 = $scope.pathNav;
        for (path in _ref1) {
          nav = _ref1[path];
          if (newPath.match(path) != null) {
            $scope.activateNav(nav);
            return true;
          }
        }
        return true;
      };
      $scope.$watch('location.path()', function(newPath, oldPath) {
        $scope.updateNav(newPath, oldPath);
        return true;
      });
      return true;
    }
  ]);

  myApp.controller('HomeCtlr', [
    '$scope', '$location', '$route', 'TeamService', 'PlayerService', function($scope, $location, $route, TeamService, PlayerService) {
      $scope.$location = $location;
      $scope.$route = $route;
      $scope.location = window.location;
      console.log("HomeCtlr");
      $scope.teams = TeamService.query({
        id: ""
      });
      $scope.players = PlayerService.query({
        id: ""
      });
      return true;
    }
  ]);

  myApp.controller('TeamCtlr', [
    '$scope', '$routeParams', '$location', '$route', 'TeamService', 'PlayerService', function($scope, $routeParams, $location, $route, TeamService, PlayerService) {
      $scope.location = $location;
      $scope.route = $route;
      $scope.winLoc = window.location;
      console.log("TeamCtlr");
      $scope.errorMsg = '';
      $scope.players = [];
      $scope.tid = $routeParams.tid;
      if (!$scope.tid) {
        $scope.tid = 1;
      }
      $scope.reloadPlayers = function() {
        var pid, player, players, _ref;

        players = [];
        _ref = $scope.team.players;
        for (pid in _ref) {
          player = _ref[pid];
          players.push(player);
        }
        $scope.players = players;
        return true;
      };
      $scope.team = TeamService.get({
        id: $scope.tid
      }, function(data, headers) {
        console.log("TeamService get success");
        console.log(data);
        console.log(headers());
        console.log($scope.team);
        $scope.tid = $scope.team.tid;
        $scope.errorMsg = '';
        $scope.reloadPlayers();
        return true;
      }, function(response) {
        var _ref, _ref1;

        console.log("TeamService get fail");
        console.log(response);
        console.log((_ref = response.data) != null ? _ref.error : void 0);
        console.log(response.headers());
        $scope.errorMsg = ((_ref1 = response.data) != null ? _ref1.error : void 0) || response.data;
        return true;
      });
      return true;
    }
  ]);

  myApp.controller('PlayerCtlr', [
    '$scope', '$routeParams', '$location', '$route', 'TeamService', 'PlayerService', function($scope, $routeParams, $location, $route, TeamService, PlayerService) {
      $scope.location = $location;
      $scope.route = $route;
      $scope.winLoc = window.location;
      console.log("PlayerCtlr");
      $scope.pid = $routeParams.pid;
      if (!$scope.pid) {
        $scope.pid = 1;
      }
      $scope.kindOptions = ['good', 'bad'];
      $scope.player = PlayerService.get({
        id: $scope.pid
      }, function(data, headers) {
        console.log("PlayerService get success");
        console.log(data);
        console.log(headers());
        return console.log($scope.player);
      }, function(response) {
        console.log("PlayerService get fail");
        console.log(response);
        return console.log(response.headers());
      });
      $scope.savePlayer = function(pid) {
        $scope.errored = false;
        $scope.alert = "";
        if ($scope.playerForm.$invalid) {
          $scope.playerForm.$dirty = true;
          $scope.errored = true;
          $scope.alert = "Some values are missing or invalid.";
          return;
        }
        return $scope.player.$put({}, function(data, headers) {
          console.log("PlayerService put success");
          console.log(data);
          return console.log(headers());
        }, function(response) {
          console.log("PlayerService put fail");
          console.log(response);
          return console.log(response.headers());
        });
      };
      return true;
    }
  ]);

  myApp.controller('DirectiveCtlr', [
    '$scope', '$location', '$route', 'TeamService', 'PlayerService', function($scope, $location, $route, TeamService, PlayerService) {
      $scope.location = $location;
      $scope.route = $route;
      $scope.winLoc = window.location;
      console.log("DirectiveCtlr");
      return true;
    }
  ]);

  jct = angular.module("jct", ['gold', 'statusActionService']);

  jct.config([
    "$provide", "$locationProvider", "$routeProvider", function($provide, $locationProvider, $routeProvider) {
      var base;

      $locationProvider.html5Mode(true);
      base = '/jct';
      $routeProvider.when("" + base + "/app", {
        templateUrl: "" + base + "/static/files/status.html",
        controller: "StatusCtlr"
      }).when("" + base + "/app/status", {
        templateUrl: "" + base + "/static/files/status.html",
        controller: "StatusCtlr"
      }).when("" + base + "/app/edit", {
        templateUrl: "" + base + "/static/files/edit.html",
        controller: "EditCtlr"
      }).when("" + base + "/app/edit/:pid", {
        templateUrl: "" + base + "/static/files/edit.html",
        controller: "EditCtlr"
      }).otherwise({
        redirectTo: "" + base + "/app"
      });
      return true;
    }
  ]);

  jct.controller('NavbarCtlr', [
    '$scope', '$routeParams', '$location', '$route', function($scope, $routeParams, $location, $route) {
      var _ref;

      $scope.location = $location;
      $scope.route = $route;
      $scope.winLoc = window.location;
      console.log("NavbarCtlr");
      $scope.alert = '';
      $scope.navActive = {
        'status': 'inactive'
      };
      if ((_ref = $scope.pathNav) == null) {
        $scope.pathNav = {
          "/app$": "status",
          "/app/status": "status"
        };
      }
      $scope.activateNav = function(nav) {
        var x;

        $scope.navActive[nav] = 'active';
        for (x in $scope.navActive) {
          if (x !== nav) {
            $scope.navActive[x] = 'inactive';
          }
        }
        return true;
      };
      $scope.updateNav = function(newPath, oldPath) {
        var nav, path, _ref1;

        _ref1 = $scope.pathNav;
        for (path in _ref1) {
          nav = _ref1[path];
          if (newPath.match(path) != null) {
            $scope.activateNav(nav);
            return true;
          }
        }
        return true;
      };
      $scope.$watch('location.path()', function(newPath, oldPath) {
        $scope.updateNav(newPath, oldPath);
        return true;
      });
      return true;
    }
  ]);

  jct.controller('StatusCtlr', [
    '$scope', '$routeParams', '$location', '$route', '$http', 'StatusActionService', function($scope, $routeParams, $location, $route, $http, StatusActionService) {
      $scope.$location = $location;
      $scope.$route = $route;
      $scope.location = window.location;
      console.log("StatusCtlr");
      $scope.alert = '';
      $scope.status = {};
      $scope.tests = [];
      $scope.failedCls = function(test) {
        if ((test != null ? test.state : void 0) === false) {
          return "error";
        }
        return "";
      };
      $scope.updateTests = function(status) {
        var name, state, tests;

        tests = [];
        for (name in status) {
          state = status[name];
          if (state === true) {
            state = 'Pass';
          } else if (state === false) {
            state = "Fail";
          } else {
            state = 'Unknown';
          }
          name = name.replace(/^test/, "");
          tests.push({
            name: name,
            state: state
          });
        }
        $scope.tests = tests;
        return true;
      };
      $scope.refreshStatus = function() {
        $scope.actionPromise = StatusActionService.call($scope, 'refresh');
        $scope.actionPromise.success(function(data, status, headers, config) {
          console.log("Edit View Refresh Promise success");
          console.log(config);
          console.log(status);
          console.log(headers());
          console.log(data);
          $scope.status = data;
          $scope.updateTests($scope.status);
          return true;
        });
        return true;
      };
      $scope.refreshStatus();
      return true;
    }
  ]);

}).call(this);
